services:
  - docker

jobs:
  include:
    - stage: "Tests"
      name: "Capybara"
      script: |
        cd capybara

        HEADLESS=1 docker-compose -f ../app/docker-compose.yml -f docker-compose.yml run --rm tests

    - name: "Cypress"
      script: |
        cd cypress

        docker-compose -f ../app/docker-compose.yml -f docker-compose.yml run --rm cypress

    - name: "Puppeteer"
      script: |
        cd puppeteer

        docker-compose run --rm tests
