version: '3.2'

# run demo app and Cypress tests in headless mode:
#
#   docker-compose -f ../app/docker-compose.yml -f docker-compose.yml run --rm cypress
#
services:

  app:
    # NOTE: see initial configs in ../app/docker-compose.yml
    build: ../app/

  cypress:
    # image from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    depends_on:
      - app
    volumes:
      - ../cypress:/cypress
    environment:
      - CYPRESS_baseUrl=http://app:8080
    working_dir: /cypress
    entrypoint: ''
    command: cypress run --spec "cypress/integration/**"
