version: '3.2'
services:
  sentimentalyzer:
    build: ./app/
    environment:
      - PORT=8123
  cypress:
    image: "cypress/included:3.3.0"
    depends_on:
      - sentimentalyzer
    environment:
      - CYPRESS_baseUrl=http://sentimentalyzer:8123
    working_dir: /cypress
    volumes:
      - ./:/cypress
