version: '3.2'
services:
  app:
    # NOTE: service configured in the file ../app/docker-compose.yml

  tests:
    build: ../puppeteer/
    volumes:
      - "../puppeteer/integration-tests:/integration-tests"
      - "../puppeteer/screenshots:/screenshots"
    command: "wait-for-it.sh app:8080 -- mocha --timeout 10000 --recursive /integration-tests"
    depends_on:
      - app
    environment:
      - APP_URL=http://app:8080
