version: '3.2'

services:

  app:
    # NOTE: service configured in the file ../app/docker-compose.yml

  tests:
    build: ../capybara/
    volumes:
      - ../capybara/:/usr/src/app/
    depends_on:
      - app
      - chrome
    environment:
      - SELENIUM_HOST=hub
      - SELENIUM_PORT=4444
      - APP_HOST=http://app:8080
      - HEADLESS=1
    entrypoint: ["./bin/test.sh"]
    command: rspec

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      VNC_NO_PASSWORD: 1

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
