version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - chrome-debug
    environment:
      - SELENIUM_HOST=hub
      - SELENIUM_PORT=4444
      - APP_HOST=http://acc-lci.ninthdecimal.com
      - HEADLESS # should be set explicitly
      - APP_USERNAME
      - APP_PASSWORD
    entrypoint: ["./bin/test.sh"]
    command: rspec

  chrome-debug:
    image: selenium/node-chrome-debug:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    ports:
      - "5900:5900"
    environment:
      HUB_HOST: hub
      VNC_NO_PASSWORD: 1

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
