version: '3.2'

# run demo app
#
#   docker-compose run --service-ports --rm app
#
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app/app/
    command: npm start
